# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def add_timed_blog(self):
    # Test name: 设定时间在简书
    # Step # | name | target | value
    # 1 | open | https://www.jianshu.com/writer#/notebooks/49575410/notes/92539713 | 
    self.driver.get("https://www.jianshu.com/writer#/notebooks/49575410/notes/92539713")
    # 2 | click | css=.\_1GsW5 > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_1GsW5 > span").click()
    # 3 | click | css=.poOXI > .fa | 
    self.driver.find_element(By.CSS_SELECTOR, ".poOXI > .fa").click()
    # 4 | click | css=.NvfK4 > .\_2po2r:nth-child(2) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".NvfK4 > .\\_2po2r:nth-child(2) > span").click()
    # 5 | click | css=.ant-calendar-picker-input | 
    self.driver.find_element(By.CSS_SELECTOR, ".ant-calendar-picker-input").click()
    # 6 | click | css=.ant-calendar-input | 
    self.driver.find_element(By.CSS_SELECTOR, ".ant-calendar-input").click()
    # 7 | type | css=.ant-calendar-input | 2022-09-24
    self.driver.find_element(By.CSS_SELECTOR, ".ant-calendar-input").send_keys("2022-09-24")
    # 8 | sendKeys | css=.ant-calendar-input | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".ant-calendar-input").send_keys(Keys.ENTER)
    # 9 | click | css=.RzhZ5 > .\_3QfkW > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".RzhZ5 > .\\_3QfkW > span").click()
  
